package com.interpretertrainer.app.ui.screens

import android.annotation.SuppressLint
import android.content.Intent
import android.net.Uri
import android.os.Handler
import android.os.Looper
import android.webkit.CookieManager
import android.webkit.JavascriptInterface
import android.webkit.WebResourceRequest
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.FilterChip
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import com.interpretertrainer.app.ai.InlinePracticeRequest
import com.interpretertrainer.app.ai.PracticeGenerationMode
import com.interpretertrainer.app.ai.PracticeTextLength
import com.interpretertrainer.app.ai.buildInlinePracticePrompt
import com.interpretertrainer.app.ai.normalizeGeneratedPracticeText
import com.interpretertrainer.app.model.LanguageOption
import com.interpretertrainer.app.privacy.AiPrivacyPreferences
import org.json.JSONObject

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun InlineAiTextGenerator(
    visible: Boolean,
    mode: PracticeGenerationMode,
    sourceLanguage: LanguageOption,
    targetLanguage: LanguageOption? = null,
    onDismiss: () -> Unit,
    onGenerated: (String) -> Unit
) {
    if (!visible) return

    val context = LocalContext.current
    var privacyAccepted by remember { mutableStateOf(AiPrivacyPreferences.hasAccepted(context)) }

    if (!privacyAccepted) {
        AlertDialog(
            onDismissRequest = onDismiss,
            title = { Text("Enable online AI generation?") },
            text = {
                Text(
                    "The selected practice mode, languages, topic, and length are sent to Puter and Qwen to generate the passage. The result is inserted only into this exercise."
                )
            },
            confirmButton = {
                Button(
                    onClick = {
                        AiPrivacyPreferences.accept(context)
                        privacyAccepted = true
                    }
                ) { Text("Enable and continue") }
            },
            dismissButton = { TextButton(onClick = onDismiss) { Text("Not now") } }
        )
        return
    }

    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    var topic by rememberSaveable { mutableStateOf("") }
    var length by rememberSaveable { mutableStateOf(PracticeTextLength.STANDARD) }
    var ready by remember { mutableStateOf(false) }
    var generating by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }
    var webView by remember { mutableStateOf<WebView?>(null) }
    val latestGenerated by rememberUpdatedState(onGenerated)
    val latestDismiss by rememberUpdatedState(onDismiss)

    val bridge = remember {
        InlineAiNativeBridge(
            onReady = { ready = true },
            onGenerated = { raw ->
                val clean = normalizeGeneratedPracticeText(raw)
                generating = false
                if (clean.isBlank()) {
                    error = "The AI returned an empty passage. Please try again."
                } else {
                    latestGenerated(clean)
                    latestDismiss()
                }
            },
            onError = { message ->
                generating = false
                error = message.ifBlank { "Could not generate a passage. Please try again." }
            }
        )
    }

    DisposableEffect(Unit) {
        onDispose {
            webView?.let { view ->
                runCatching { view.stopLoading() }
                runCatching { view.removeJavascriptInterface("InlineAiNative") }
                runCatching { view.destroy() }
            }
            webView = null
        }
    }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 20.dp),
            verticalArrangement = Arrangement.spacedBy(14.dp)
        ) {
            Column(
                modifier = Modifier.fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
                    Text("Generate inside this exercise", style = MaterialTheme.typography.titleLarge)
                }
                Text(
                    "${mode.title} · ${sourceLanguage.label}" +
                        targetLanguage?.takeIf { it != sourceLanguage }?.let { " → ${it.label}" }.orEmpty(),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            HorizontalDivider()

            OutlinedTextField(
                value = topic,
                onValueChange = { topic = it; error = null },
                modifier = Modifier.fillMaxWidth(),
                label = { Text("Topic (optional)") },
                placeholder = { Text("e.g. climate policy, education, diplomacy") },
                singleLine = true,
                shape = RoundedCornerShape(16.dp)
            )

            Column(verticalArrangement = Arrangement.spacedBy(7.dp)) {
                Text("Length", style = MaterialTheme.typography.labelLarge)
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    PracticeTextLength.entries.forEach { option ->
                        FilterChip(
                            selected = length == option,
                            onClick = { length = option },
                            label = { Text(option.label) },
                            modifier = Modifier.weight(1f)
                        )
                    }
                }
                Text(
                    "Approximately ${length.targetWords} words",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            error?.let {
                Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
            }

            Button(
                onClick = {
                    val prompt = buildInlinePracticePrompt(
                        InlinePracticeRequest(
                            mode = mode,
                            sourceLanguage = sourceLanguage.label,
                            targetLanguage = targetLanguage?.label,
                            topic = topic,
                            length = length
                        )
                    )
                    error = null
                    generating = true
                    webView?.evaluateJavascript(
                        "window.generatePracticeText(${JSONObject.quote(prompt)}, ${length.maxTokens});",
                        null
                    )
                },
                enabled = ready && !generating,
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(18.dp)
            ) {
                if (generating) {
                    CircularProgressIndicator(modifier = Modifier.size(19.dp), strokeWidth = 2.dp)
                    Text("  Generating…")
                } else {
                    Icon(Icons.Default.AutoAwesome, contentDescription = null)
                    Text(if (ready) "  Generate passage" else "  Connecting…")
                }
            }

            InlineGeneratorWebView(
                onCreated = { webView = it },
                bridge = bridge
            )
            Spacer(Modifier.height(10.dp))
        }
    }
}

private class InlineAiNativeBridge(
    private val onReady: () -> Unit,
    private val onGenerated: (String) -> Unit,
    private val onError: (String) -> Unit
) {
    private val mainHandler = Handler(Looper.getMainLooper())

    @JavascriptInterface
    fun onReady(@Suppress("UNUSED_PARAMETER") value: String) = mainHandler.post { onReady() }

    @JavascriptInterface
    fun onGenerated(value: String) = mainHandler.post { onGenerated(value) }

    @JavascriptInterface
    fun onError(value: String) = mainHandler.post { onError(value) }
}

@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun InlineGeneratorWebView(
    bridge: InlineAiNativeBridge,
    onCreated: (WebView) -> Unit
) {
    val context = LocalContext.current

    AndroidView(
        modifier = Modifier
            .size(1.dp)
            .alpha(0f)
            .clearAndSetSemantics { },
        factory = { webContext ->
            WebView(webContext).apply {
                val inlineView = this
                configureCoachWebView(this)
                addJavascriptInterface(bridge, "InlineAiNative")
                webViewClient = object : WebViewClient() {
                    override fun shouldOverrideUrlLoading(view: WebView?, request: WebResourceRequest?): Boolean {
                        val uri = request?.url ?: return true
                        if (!request.isForMainFrame) return false
                        if (uri.scheme.equals("https", true) && uri.host.equals("interpreter-trainer.app", true)) return false
                        if (request.hasGesture() && uri.scheme.equals("https", true)) {
                            runCatching { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(uri.toString()))) }
                        }
                        return true
                    }
                }
                webChromeClient = CoachChromeClient(webContext)
                CookieManager.getInstance().apply {
                    setAcceptCookie(true)
                    setAcceptThirdPartyCookies(inlineView, true)
                }
                val html = webContext.assets.open("interpreter_inline_generator.html")
                    .bufferedReader(Charsets.UTF_8)
                    .use { it.readText() }
                loadDataWithBaseURL("https://interpreter-trainer.app/", html, "text/html", "UTF-8", null)
                onCreated(this)
            }
        }
    )
}
